name: Release Plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: release # Use the release branch for building releases

      - name: Package Release Artifact
        run: |
          mkdir habsiad
          cp main.js manifest.json styles.css habsiad/
          zip -r habsiad.zip habsiad/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            habsiad.zip
