name: Release Plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust if needed

      - name: Install Dependencies
        run: npm install

      - name: Build Plugin
        run: npm run build

      - name: Package Release Artifact
        run: zip plugin-release.zip main.js manifest.json styles.css

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            plugin-release.zip
